import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Explore Free Courses & Learning Roadmaps | Smart Learning Platform',
  description: 'Browse 500+ free courses and learning roadmaps. Learn programming, Python, JavaScript, React, web development, data science, machine learning, cybersecurity, business, science, languages & more. Expert-curated content with smart personalized learning paths.',
  keywords: [
    'programming courses',
    'coding bootcamp',
    'web development course',
    'data science training',
    'python course',
    'javascript tutorial',
    'react training',
    'machine learning course',
    'cybersecurity training',
    'cloud computing course',
    'free programming courses',
    'learn to code',
    'coding tutorial',
    'programming roadmap',
    'tech skills training',
    'software development course',
    'computer science course',
    'programming for beginners',
    'advanced programming',
    'coding practice',
    'programming fundamentals',
    'full stack development',
    'backend development',
    'frontend development',
    'mobile app development',
    'game development',
    'DevOps training',
    'database course',
    'system design',
    'competitive programming',
    'algorithm practice',
    'coding interview prep'
  ],
  openGraph: {
    title: 'Explore 500+ Free Programming Courses & Tech Learning Roadmaps',
    description: 'Master programming skills with expert-curated learning paths. Free courses in Python, JavaScript, React, data science, machine learning & more. Start learning today!',
    url: 'https://menttor.live/explore',
    type: 'website',
    images: [
      {
        url: '/og-explore.png',
        width: 1200,
        height: 630,
        alt: 'Explore Programming Courses - Menttor Smart Learning Platform',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Free Programming Courses & Tech Training | Menttor Explore',
    description: 'Browse 500+ expert-curated programming courses. Learn Python, JavaScript, React, data science & more with smart learning roadmaps.',
    images: ['/og-explore.png'],
  },
  alternates: {
    canonical: '/explore',
  },
}