"""Add save and share fields to learning_content table

Revision ID: fe0dfa06994f
Revises: 5686bef7003e
Create Date: 2025-08-17 11:03:28.434077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fe0dfa06994f'
down_revision: Union[str, Sequence[str], None] = '5686bef7003e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Clear all existing data from learningcontent table to avoid NOT NULL constraint issues (if table exists)
    try:
        op.execute("DELETE FROM learningcontent")
    except Exception:
        # Table doesn't exist yet, skip the deletion
        pass
    
    op.add_column('learningcontent', sa.Column('is_saved', sa.Boolean(), nullable=False))
    op.add_column('learningcontent', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('learningcontent', sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('learningcontent', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('learningcontent', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('learningcontent', sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('learningcontent', sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('learningcontent', sa.Column('subtopic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_learningcontent_share_token'), 'learningcontent', ['share_token'], unique=False)
    op.create_index(op.f('ix_learningcontent_subtopic_id'), 'learningcontent', ['subtopic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learningcontent_subtopic_id'), table_name='learningcontent')
    op.drop_index(op.f('ix_learningcontent_share_token'), table_name='learningcontent')
    op.drop_column('learningcontent', 'subtopic_id')
    op.drop_column('learningcontent', 'goal')
    op.drop_column('learningcontent', 'subject')
    op.drop_column('learningcontent', 'updated_at')
    op.drop_column('learningcontent', 'created_at')
    op.drop_column('learningcontent', 'share_token')
    op.drop_column('learningcontent', 'is_public')
    op.drop_column('learningcontent', 'is_saved')
    # ### end Alembic commands ###
